spring:
  application:
    name: mes_backend
  datasource:
    url: jdbc:mysql://localhost:3306/mess_db?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: "1234"
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
  profiles:
    active:
      - dev

# MyBatis-Plus 配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.mes.entity

# 日志配置
logging:
  level:
    com.example.mes: DEBUG
